# Generated by Django 5.2.14 on 2026-05-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ergon', '0003_advance_expense_nullable_project_rejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='actual_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='execution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='execution_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='is_rollover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='original_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='rollover_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='rollover_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='sla_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='timer_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='total_paused_duration',
            field=models.IntegerField(default=0),
        ),
    ]
