# Generated by Django 5.2.14 on 2026-05-23 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ergon', '0004_dailytask_actual_time_dailytask_execution_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='followup',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='attachments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='completion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='escalation_delay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='followup',
            name='escalation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='followup_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='followup',
            name='linked_department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='followup',
            name='linked_module',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='followup',
            name='linked_project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='meeting_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='followup',
            name='related_incident',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='followup',
            name='related_inspection',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='followup',
            name='related_quality_finding',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='followup',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='reminder_frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='followup',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='followup_type',
            field=models.CharField(choices=[('standalone', 'Standalone Follow-up'), ('task', 'Task Follow-up'), ('client', 'Client Follow-up'), ('vendor', 'Vendor Follow-up'), ('employee', 'Employee Follow-up'), ('inspection', 'Inspection Follow-up'), ('incident', 'Incident Follow-up'), ('capa', 'CAPA Follow-up'), ('quality', 'Quality Follow-up')], default='task', max_length=20),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('open', 'Open'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('escalated', 'Escalated'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='open', max_length=50),
        ),
    ]
