# Generated by Django 5.2.11 on 2026-02-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('account_locked', 'Account Locked'), ('tenant_created', 'Tenant Created'), ('tenant_disabled', 'Tenant Disabled'), ('subscription_changed', 'Subscription Changed'), ('master_created', 'Master Created'), ('master_disabled', 'Master Disabled'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_status_changed', 'Project Status Changed'), ('project_member_added', 'Project Member Added'), ('project_member_updated', 'Project Member Updated'), ('project_member_removed', 'Project Member Removed')], max_length=50),
        ),
    ]
