# Generated by Django 5.2.11 on 2026-02-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_type',
            field=models.CharField(blank=True, choices=[('master', 'Master Admin'), ('masteradmin', 'Master Admin'), ('client', 'Client Admin'), ('epc', 'EPC Admin'), ('contractor', 'Contractor Admin')], help_text='Admin type for Athens module access', max_length=20, null=True),
        ),
    ]
