# Generated by Django 5.2.11 on 2026-02-07 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_admin_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.UUIDField(blank=True, null=True)),
                ('client_company_id', models.UUIDField(blank=True, null=True)),
                ('epc_company_id', models.UUIDField(blank=True, null=True)),
                ('contractor_company_ids', models.JSONField(default=list)),
                ('projectName', models.CharField(max_length=255)),
                ('projectCategory', models.CharField(choices=[('governments', 'Governments'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('chemical', 'Chemical'), ('port_and_maritime', 'Port and Maritime'), ('power_and_energy', 'Power and Energy'), ('logistics', 'Logistics'), ('schools', 'Schools'), ('mining', 'Mining'), ('oil_and_gas', 'Oil & Gas'), ('shopping_mall', 'Shopping Mall'), ('aviation', 'Aviation')], max_length=20)),
                ('capacity', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('nearestPoliceStation', models.CharField(max_length=255)),
                ('nearestPoliceStationContact', models.CharField(max_length=255)),
                ('nearestHospital', models.CharField(max_length=255)),
                ('nearestHospitalContact', models.CharField(max_length=255)),
                ('commencementDate', models.DateField()),
                ('deadlineDate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication.project'),
        ),
    ]
