# Generated by Django 5.2.11 on 2026-02-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_project_user_created_by_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='athens_tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Tenant ID for MasterAdmin scoping', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_type',
            field=models.CharField(blank=True, choices=[('client', 'Client Admin'), ('epc', 'EPC Admin'), ('contractor', 'Contractor Admin')], help_text='Admin type for Athens module access', max_length=20, null=True),
        ),
    ]
