# Generated manually for Athens 2.0 Create Admin Parity

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_add_masteradmin_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name for project admin', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registered_address',
            field=models.TextField(blank=True, help_text='Registered office address', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_autogenerated_password',
            field=models.BooleanField(default=False, help_text='Whether password was auto-generated'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_password_reset_required',
            field=models.BooleanField(default=False, help_text='Whether user must reset password on first login'),
        ),
    ]
