# Generated by Django 5.2.11 on 2026-02-12 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_add_company_fields'),
        ('control_plane', '0006_add_tenant_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant for MasterAdmin scoping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masteradmin_users', to='control_plane.tenant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='athens_tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='DEPRECATED: Legacy tenant ID. Use tenant FK.', null=True),
        ),
    ]
