# Generated by Django 5.2.11 on 2026-02-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_migrate_tenant_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='epc_company_id',
        ),
        migrations.AddField(
            model_name='project',
            name='epc_company_ids',
            field=models.JSONField(default=list, help_text='List of EPC company IDs (multiple allowed if client is subscriber)'),
        ),
        migrations.AddField(
            model_name='project',
            name='subscriber_role',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('epc', 'EPC')], help_text='Who is the subscriber: Client or EPC', max_length=10, null=True),
        ),
    ]
