# Generated by Django 5.2.11 on 2026-02-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_make_project_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_company_id',
            field=models.UUIDField(blank=True, help_text='Single client company (only one allowed)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='contractor_company_ids',
            field=models.JSONField(default=list, help_text='List of contractor company IDs (unlimited)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='epc_company_ids',
            field=models.JSONField(default=list, help_text='List of EPC company IDs (multiple if client subscriber, max 1 if EPC subscriber)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subscriber_role',
            field=models.CharField(choices=[('client', 'Client'), ('epc', 'EPC')], help_text='Who is the subscriber: Client or EPC (REQUIRED)', max_length=10),
        ),
    ]
