# Generated by Django 5.2.11 on 2026-02-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_project_client_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(upload_to='company_logos/', null=True, blank=True),
        ),
    ]
