# Generated by Django 5.2.14 on 2026-05-11 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_induction_training_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='induction_attended',
            field=models.BooleanField(default=False, help_text='Whether user attended offline induction training (marked by admin)'),
        ),
        migrations.AddField(
            model_name='user',
            name='induction_attended_at',
            field=models.DateTimeField(blank=True, help_text='When admin marked induction attendance', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='induction_marked_by',
            field=models.ForeignKey(blank=True, help_text='Admin who marked induction attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_inductions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending_profile', 'Pending Profile'), ('pending_approval', 'Pending Approval'), ('approved_pending_induction', 'Approved - Pending Induction'), ('active', 'Active')], default='active', help_text='User onboarding status for access control', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='subscriber_role',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('epc', 'EPC')], help_text='Who is the subscriber: Client or EPC (REQUIRED)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='induction_completed',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use induction_attended instead'),
        ),
        migrations.AlterField(
            model_name='user',
            name='induction_completed_at',
            field=models.DateTimeField(blank=True, help_text='DEPRECATED: Use induction_attended_at instead', null=True),
        ),
    ]
