# Generated by Django 5.2.11 on 2026-02-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_add_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='company_logos/'),
        ),
    ]
