# Generated by Django 5.2.11 on 2026-02-20 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_remove_project_contractor_epc_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractor_company_ids',
            field=models.JSONField(default=list, help_text='List of contractor company IDs (unlimited)'),
        ),
        migrations.AddField(
            model_name='project',
            name='epc_company_ids',
            field=models.JSONField(default=list, help_text='List of EPC company IDs (multiple if client subscriber, max 1 if EPC subscriber)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
