# Generated by Django 5.2.11 on 2026-02-22 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_project_contractor_company_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthensTenant',
            fields=[
                ('id', models.UUIDField(help_text='Unique tenant identifier generated by SAP', primary_key=True, serialize=False, verbose_name='Athens Tenant ID')),
                ('company_id', models.UUIDField(blank=True, help_text='Optional reference to legacy company identifier', null=True, verbose_name='Company ID')),
                ('master_admin_id', models.UUIDField(help_text='Master admin user ID from SAP', verbose_name='Master Admin ID')),
                ('enabled_modules', models.JSONField(default=list, help_text='List of enabled modules for this tenant', verbose_name='Enabled Modules')),
                ('enabled_menus', models.JSONField(default=list, help_text='List of enabled menus for this tenant', verbose_name='Enabled Menus')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant is active and can access Athens', verbose_name='Is Active')),
                ('tenant_name', models.CharField(blank=True, help_text='Human-readable tenant name for identification', max_length=255, verbose_name='Tenant Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Athens Tenant',
                'verbose_name_plural': 'Athens Tenants',
                'db_table': 'athens_tenant',
                'indexes': [models.Index(fields=['master_admin_id'], name='athens_tena_master__2288f8_idx'), models.Index(fields=['is_active'], name='athens_tena_is_acti_19ab61_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Tenant Created'), ('activated', 'Tenant Activated'), ('deactivated', 'Tenant Deactivated'), ('module_enabled', 'Module Enabled'), ('module_disabled', 'Module Disabled'), ('menu_enabled', 'Menu Enabled'), ('menu_disabled', 'Menu Disabled'), ('master_admin_changed', 'Master Admin Changed'), ('updated', 'Tenant Updated')], max_length=30, verbose_name='Action')),
                ('description', models.TextField(help_text='Detailed description of the action', verbose_name='Description')),
                ('previous_value', models.JSONField(blank=True, help_text='Previous value before change', null=True, verbose_name='Previous Value')),
                ('new_value', models.JSONField(blank=True, help_text='New value after change', null=True, verbose_name='New Value')),
                ('performed_by', models.UUIDField(blank=True, help_text='User ID who performed the action', null=True, verbose_name='Performed By')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='authentication.athenstenant')),
            ],
            options={
                'verbose_name': 'Tenant Audit Log',
                'verbose_name_plural': 'Tenant Audit Logs',
                'db_table': 'tenant_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', '-timestamp'], name='tenant_audi_tenant__f28a40_idx'), models.Index(fields=['action'], name='tenant_audi_action_7cadd7_idx')],
            },
        ),
    ]
