# Generated by Django 5.2.11 on 2026-02-22 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_import_tenant_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.UUIDField(blank=True, help_text='Athens tenant identifier for multi-tenant isolation', null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='admin_photos/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='admin_logos/')),
                ('signature_template', models.ImageField(blank=True, null=True, upload_to='admin_signature_templates/')),
                ('signature_template_data', models.JSONField(blank=True, help_text='Stores template configuration data', null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_admin_details', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_details',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.UUIDField(blank=True, help_text='Athens tenant identifier for multi-tenant isolation', null=True)),
                ('employee_id', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('father_or_spouse_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('education_level', models.CharField(blank=True, max_length=255)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('uan', models.CharField(blank=True, max_length=100)),
                ('pan', models.CharField(blank=True, max_length=100)),
                ('pan_attachment', models.FileField(blank=True, null=True, upload_to='pan_attachments/')),
                ('aadhaar', models.CharField(blank=True, max_length=100)),
                ('aadhaar_attachment', models.FileField(blank=True, null=True, upload_to='aadhaar_attachments/')),
                ('mark_of_identification', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('specimen_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signature_template', models.ImageField(blank=True, null=True, upload_to='signature_templates/')),
                ('signature_template_data', models.JSONField(blank=True, help_text='Stores template configuration data', null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_user_details', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
