# Generated by Django 5.2.11 on 2026-02-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_notificationpreference_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.project'),
        ),
    ]
