# Generated by Django 5.2.11 on 2026-02-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_fix_user_project_cascade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
    ]
