# Generated by Django 5.2.12 on 2026-04-15 07:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_remove_notificationpreference_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('meeting_notifications', models.BooleanField(default=True)),
                ('approval_notifications', models.BooleanField(default=True)),
                ('general_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('meeting', 'Meeting'), ('meeting_response', 'Meeting Response'), ('action_item', 'Action Item'), ('general', 'General'), ('approval', 'Approval'), ('meeting_invitation', 'Meeting Invitation'), ('meeting_scheduled', 'Meeting Scheduled'), ('mom_created', 'MOM Created'), ('chat_message', 'Chat Message'), ('chat_message_delivered', 'Chat Message Delivered'), ('chat_message_read', 'Chat Message Read'), ('chat_file_shared', 'Chat File Shared'), ('safety_observation_assigned', 'Safety Observation Assigned'), ('safety_observation_commitment', 'Safety Observation Commitment'), ('safety_observation_completed', 'Safety Observation Completed'), ('safety_observation_approved', 'Safety Observation Approved'), ('safety_observation_closed', 'Safety Observation Closed'), ('ptw_verification', 'PTW Verification Required'), ('ptw_approval', 'PTW Approval Required'), ('ptw_approved', 'PTW Approved'), ('ptw_rejected', 'PTW Rejected'), ('ptw_expiring', 'PTW Expiring Soon'), ('permission_request', 'Permission Request'), ('permission_approved', 'Permission Approved'), ('permission_denied', 'Permission Denied')], default='general', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_auth_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='authenticat_user_id_a05277_idx'), models.Index(fields=['user', 'read'], name='authenticat_user_id_77da2c_idx'), models.Index(fields=['user', 'notification_type'], name='authenticat_user_id_4528f8_idx')],
            },
        ),
    ]
