# Generated by Django 5.2.13 on 2026-05-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_remove_user_subscription_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Approval status for regular users created by project admins', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='company_type',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('epc', 'EPC'), ('contractor', 'Contractor')], help_text='Company type: client / epc / contractor', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=False, help_text='True until user completes profile form on first login'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='admin', help_text='admin = project admin, user = regular user created by project admin', max_length=10),
        ),
    ]
