# Generated by Django 5.2.14 on 2026-05-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_user_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Whether user must change password before accessing modules (set after induction completion)'),
        ),
    ]
