from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from authentication.models import User, UserType, SecurityLog
from authentication.permissions import IsCompanyUser
import random, string


class IsProjectAdmin(IsCompanyUser):
    def has_permission(self, request, view):
        return super().has_permission(request, view) and bool(getattr(request.user, 'admin_type', None))


def _gen_password(length=12):
    return ''.join(random.choices(string.ascii_letters + string.digits + '!@#$%', k=length))


# ── User Management ──────────────────────────────────────────────────────────

@api_view(['GET', 'POST'])
@permission_classes([IsAuthenticated, IsProjectAdmin])
def users_list_create(request):
    admin = request.user
    if request.method == 'GET':
        qs = User.objects.filter(created_by=admin, role_type='user').values(
            'id', 'username', 'email', 'name', 'surname', 'department',
            'designation', 'phone_number', 'company_type', 'approval_status',
            'is_first_login', 'is_active', 'created_at'
        )
        return Response(list(qs))

    username = (request.data.get('username') or '').strip()
    email = (request.data.get('email') or f'{username}@temp.local').strip()
    if not username:
        return Response({'error': 'username is required'}, status=400)
    if User.objects.filter(username=username).exists():
        return Response({'error': 'Username already exists'}, status=400)
    if User.objects.filter(email=email).exists():
        return Response({'error': 'Email already exists'}, status=400)

    password = _gen_password()
    user = User.objects.create(
        username=username, email=email,
        name=request.data.get('name', ''),
        user_type=UserType.COMPANYUSER,
        role_type='user',
        company_type=admin.admin_type,
        admin_type=None,
        project=admin.project,
        tenant=admin.tenant,
        company_id=admin.company_id,
        athens_tenant_id=admin.athens_tenant_id,
        created_by=admin,
        approval_status='pending',
        is_first_login=True,
        is_autogenerated_password=True,
        is_active=True,
    )
    user.set_password(password)
    user.save()
    SecurityLog.objects.create(
        event_type=SecurityLog.EventType.MASTER_CREATED,
        severity=SecurityLog.Severity.INFO,
        user=admin,
        metadata={'event': 'projectadmin.create_user', 'created_user_id': user.id}
    )
    return Response({'id': user.id, 'username': user.username, 'email': user.email,
                     'password': password, 'company_type': user.company_type,
                     'approval_status': user.approval_status}, status=201)


@api_view(['DELETE'])
@permission_classes([IsAuthenticated, IsProjectAdmin])
def user_delete(request, user_id):
    try:
        User.objects.get(id=user_id, created_by=request.user, role_type='user').delete()
        return Response(status=204)
    except User.DoesNotExist:
        return Response({'error': 'User not found'}, status=404)


@api_view(['POST'])
@permission_classes([IsAuthenticated, IsProjectAdmin])
def user_reset_password(request, user_id):
    try:
        user = User.objects.get(id=user_id, created_by=request.user, role_type='user')
        password = _gen_password()
        user.set_password(password)
        user.is_first_login = True
        user.save()
        return Response({'password': password})
    except User.DoesNotExist:
        return Response({'error': 'User not found'}, status=404)


# ── Approval Workflow ─────────────────────────────────────────────────────────

@api_view(['GET'])
@permission_classes([IsAuthenticated, IsProjectAdmin])
def pending_approvals(request):
    qs = User.objects.filter(
        created_by=request.user, role_type='user', approval_status='pending'
    ).values('id', 'username', 'email', 'name', 'surname', 'department',
             'designation', 'phone_number', 'company_type', 'created_at')
    return Response(list(qs))


@api_view(['POST'])
@permission_classes([IsAuthenticated, IsProjectAdmin])
def approve_user(request, user_id):
    try:
        user = User.objects.get(id=user_id, created_by=request.user, role_type='user')
        user.approval_status = 'approved'
        user.is_active = True
        user.save()
        return Response({'message': 'User approved', 'approval_status': 'approved'})
    except User.DoesNotExist:
        return Response({'error': 'User not found'}, status=404)


@api_view(['POST'])
@permission_classes([IsAuthenticated, IsProjectAdmin])
def reject_user(request, user_id):
    try:
        user = User.objects.get(id=user_id, created_by=request.user, role_type='user')
        user.approval_status = 'rejected'
        user.is_active = False
        user.save()
        return Response({'message': 'User rejected', 'approval_status': 'rejected'})
    except User.DoesNotExist:
        return Response({'error': 'User not found'}, status=404)


# ── Profile Completion (regular user first login) ─────────────────────────────

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def complete_profile(request):
    user = request.user
    if user.role_type != 'user':
        return Response({'error': 'Only regular users can complete profile'}, status=403)
    d = request.data
    user.name        = d.get('name', user.name or '')
    user.surname     = d.get('surname', user.surname or '')
    user.phone_number = d.get('phone', user.phone_number or '')
    user.department  = d.get('department', user.department or '')
    user.designation = d.get('designation', user.designation or '')
    user.is_first_login = False
    user.save()
    return Response({
        'message': 'Profile submitted. Waiting for admin approval.',
        'approval_status': user.approval_status,
        'is_first_login': False,
    })


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def my_status(request):
    u = request.user
    return Response({
        'role_type': u.role_type,
        'approval_status': u.approval_status,
        'is_first_login': u.is_first_login,
        'company_type': u.company_type,
        'admin_type': u.admin_type,
    })
