# Generated by Django 5.2.5 on 2025-08-28 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('conducted_by', models.CharField(max_length=255, verbose_name='Conducted By')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_induction_trainings', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='induction_trainings', to='authentication.project')),
            ],
            options={
                'verbose_name': 'Induction Training',
                'verbose_name_plural': 'Induction Trainings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InductionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.IntegerField(verbose_name='Worker ID')),
                ('worker_name', models.CharField(max_length=255, verbose_name='Worker Name')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('induction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='inductiontraining.inductiontraining')),
            ],
            options={
                'verbose_name': 'Induction Attendance',
                'verbose_name_plural': 'Induction Attendances',
                'unique_together': {('induction', 'worker_id')},
            },
        ),
    ]
