# Generated by Django 5.2.1 on 2025-12-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inductiontraining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionattendance',
            name='attendance_photo',
            field=models.TextField(blank=True, null=True, verbose_name='Attendance Photo'),
        ),
        migrations.AddField(
            model_name='inductionattendance',
            name='match_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Photo Match Score'),
        ),
        migrations.AddField(
            model_name='inductionattendance',
            name='participant_type',
            field=models.CharField(choices=[('worker', 'Worker'), ('user', 'User')], default='worker', max_length=20, verbose_name='Participant Type'),
        ),
        migrations.AddField(
            model_name='inductionattendance',
            name='worker_photo',
            field=models.TextField(blank=True, null=True, verbose_name='Worker Photo URL'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='evidence_photo',
            field=models.TextField(blank=True, null=True, verbose_name='Evidence Photo'),
        ),
    ]
