# Generated by Django 5.2.1 on 2025-12-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inductiontraining', '0002_inductionattendance_attendance_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductiontraining',
            name='duration',
            field=models.PositiveIntegerField(default=60, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='duration_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours')], default='minutes', max_length=10, verbose_name='Duration Unit'),
        ),
    ]
