# Generated by Django 5.2.1 on 2025-12-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inductiontraining', '0003_inductiontraining_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductiontraining',
            name='dept_head_date',
            field=models.DateField(blank=True, null=True, verbose_name='Department Head Signature Date'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='dept_head_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Department Head Name'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='dept_head_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Department Head Signature'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='document_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Document ID'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='hr_date',
            field=models.DateField(blank=True, null=True, verbose_name='HR Signature Date'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='hr_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='HR Representative Name'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='hr_signature',
            field=models.TextField(blank=True, null=True, verbose_name='HR Representative Signature'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='revision_number',
            field=models.CharField(default='00', max_length=10, verbose_name='Revision Number'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='safety_date',
            field=models.DateField(blank=True, null=True, verbose_name='Safety Signature Date'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='safety_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Safety Officer Name'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='safety_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Safety Officer Signature'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='trainer_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Trainer Digital Signature'),
        ),
    ]
