# Generated by Django 5.2.1 on 2025-12-28 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inductiontraining', '0004_inductiontraining_dept_head_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inductiontraining',
            name='dept_head_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='hr_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='safety_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='trainer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inductiontraining',
            name='dept_head_date',
            field=models.DateField(blank=True, null=True, verbose_name='Quality Officer Signature Date'),
        ),
        migrations.AlterField(
            model_name='inductiontraining',
            name='dept_head_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Quality Officer Name'),
        ),
        migrations.AlterField(
            model_name='inductiontraining',
            name='dept_head_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Quality Officer Signature'),
        ),
    ]
