# Generated by Django 5.2.9 on 2026-01-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inductiontraining', '0002_add_athens_tenant_id'),
        ('inductiontraining', '0005_inductiontraining_dept_head_user_and_more'),
    ]

    operations = [
    ]
