# Generated by Django 5.2.9 on 2026-01-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inductiontraining', '0006_merge_20260103_1152'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inductionattendance',
            name='induction_attendance_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='inductiontraining',
            name='induction_training_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='inductiontraining',
            name='induction_training_tenant_status_idx',
        ),
        migrations.RemoveField(
            model_name='inductionattendance',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='inductiontraining',
            name='athens_tenant_id',
        ),
    ]
