# Generated by Codex on 2026-01-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inductiontraining', '0007_remove_inductionattendance_induction_attendance_tenant_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductiontraining',
            name='join_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Join Code'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='qr_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='QR Token'),
        ),
        migrations.AddField(
            model_name='inductiontraining',
            name='qr_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='QR Expires At'),
        ),
    ]
