#!/bin/bash

# Create Admin Parity - Implementation Verification Script
# Run this script to verify the implementation is working correctly

echo "=========================================="
echo "Create Admin Parity - Verification Script"
echo "=========================================="
echo ""

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check backend migration
echo "1. Checking backend migration..."
cd /var/www/athens-2.0/backend
MIGRATION_CHECK=$(python3 manage.py showmigrations authentication 2>&1 | grep "0007_add_company_fields")
if [[ $MIGRATION_CHECK == *"[X]"* ]]; then
    echo -e "${GREEN}✓${NC} Migration 0007_add_company_fields applied"
else
    echo -e "${RED}✗${NC} Migration not applied. Run: python3 manage.py migrate authentication"
    exit 1
fi

# Check model fields
echo ""
echo "2. Checking User model fields..."
if grep -q "company_name" authentication/models.py && \
   grep -q "registered_address" authentication/models.py && \
   grep -q "is_autogenerated_password" authentication/models.py && \
   grep -q "is_password_reset_required" authentication/models.py; then
    echo -e "${GREEN}✓${NC} All required fields present in User model"
else
    echo -e "${RED}✗${NC} Missing fields in User model"
    exit 1
fi

# Check serializers
echo ""
echo "3. Checking serializers..."
if grep -q "ProjectAdminCreateSerializer" authentication/masteradmin/serializers.py; then
    echo -e "${GREEN}✓${NC} ProjectAdminCreateSerializer exists"
else
    echo -e "${RED}✗${NC} ProjectAdminCreateSerializer not found"
    exit 1
fi

# Check views
echo ""
echo "4. Checking views..."
if grep -q "create_project_admin" authentication/masteradmin/views.py && \
   grep -q "project_admins" authentication/masteradmin/views.py; then
    echo -e "${GREEN}✓${NC} New endpoints exist in views"
else
    echo -e "${RED}✗${NC} Missing endpoints in views"
    exit 1
fi

# Check URLs
echo ""
echo "5. Checking URL routes..."
if grep -q "create-project-admin" authentication/masteradmin/urls.py && \
   grep -q "project_id>/admins" authentication/masteradmin/urls.py; then
    echo -e "${GREEN}✓${NC} New routes configured"
else
    echo -e "${RED}✗${NC} Missing routes in urls.py"
    exit 1
fi

# Check frontend service
echo ""
echo "6. Checking frontend service..."
cd /var/www/athens-2.0/frontend
if grep -q "createProjectAdmin" src/services/masteradmin.ts && \
   grep -q "getProjectAdmins" src/services/masteradmin.ts && \
   grep -q "ProjectAdminCreateRequest" src/services/masteradmin.ts; then
    echo -e "${GREEN}✓${NC} Frontend service methods exist"
else
    echo -e "${RED}✗${NC} Missing methods in frontend service"
    exit 1
fi

# Check AdminUsers page
echo ""
echo "7. Checking AdminUsers page..."
if grep -q "project_id" src/pages/masteradmin/AdminUsers.tsx && \
   grep -q "admin_type" src/pages/masteradmin/AdminUsers.tsx && \
   grep -q "company_name" src/pages/masteradmin/AdminUsers.tsx && \
   grep -q "registered_address" src/pages/masteradmin/AdminUsers.tsx && \
   grep -q "downloadCredentials" src/pages/masteradmin/AdminUsers.tsx; then
    echo -e "${GREEN}✓${NC} AdminUsers page has all required fields"
else
    echo -e "${RED}✗${NC} Missing fields in AdminUsers page"
    exit 1
fi

# Check frontend build
echo ""
echo "8. Checking frontend build..."
if [ -d "dist" ]; then
    echo -e "${GREEN}✓${NC} Frontend build exists"
else
    echo -e "${YELLOW}⚠${NC} Frontend not built. Run: npm run build"
fi

echo ""
echo "=========================================="
echo -e "${GREEN}✓ All checks passed!${NC}"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Start backend: cd /var/www/athens-2.0/backend && python3 manage.py runserver 0.0.0.0:8004"
echo "2. Start frontend: cd /var/www/athens-2.0/frontend && npm run dev"
echo "3. Login as MasterAdmin"
echo "4. Navigate to Admin Users"
echo "5. Click 'Create Admin User'"
echo "6. Fill form with:"
echo "   - Project: Select a project"
echo "   - Admin Type: client/epc/contractor"
echo "   - Username: test_admin"
echo "   - Company Name: Test Company"
echo "   - Registered Address: 123 Test Street"
echo "7. Submit and verify credentials download"
echo ""
echo "API Endpoint:"
echo "POST /api/auth/masteradmin/admin-users/create-project-admin/"
echo ""
echo "Documentation:"
echo "- CREATE_ADMIN_PARITY_IMPLEMENTATION_COMPLETE.md"
echo "- ORIGINAL_ATHENS_CREATE_ADMIN_SPEC.md"
echo ""
