# Generated by Django 5.2.13 on 2026-04-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0002_riskassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
