import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Eye, EyeOff, Lock, ShieldCheck } from 'lucide-react'
import toast from 'react-hot-toast'
import { apiClient } from '../../lib/api'
import { useAuthStore } from '../../store/authStore'

const PASSWORD_RULES = [
  { label: 'At least 8 characters', test: (value: string) => value.length >= 8 },
  { label: 'One uppercase letter (A–Z)', test: (value: string) => /[A-Z]/.test(value) },
  { label: 'One lowercase letter (a–z)', test: (value: string) => /[a-z]/.test(value) },
  { label: 'One number (0–9)', test: (value: string) => /\d/.test(value) },
  { label: 'One special character (@$!%*?&#^()_-+=)', test: (value: string) => /[@$!%*?&#^()_\-+=]/.test(value) },
]

function getStrength(value: string) {
  return PASSWORD_RULES.filter(rule => rule.test(value)).length
}

const ChangePasswordPage: React.FC = () => {
  const navigate = useNavigate()
  const { updateUser, setMustChangePassword, refreshCurrentUser } = useAuthStore()
  const [currentPassword, setCurrentPassword] = useState('')
  const [newPassword, setNewPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [showCurrent, setShowCurrent] = useState(false)
  const [showNew, setShowNew] = useState(false)
  const [showConfirm, setShowConfirm] = useState(false)
  const [loading, setLoading] = useState(false)

  const passwordStrength = getStrength(newPassword)
  const passwordMatches = newPassword && confirmPassword === newPassword
  const allRulesMet = passwordStrength === PASSWORD_RULES.length

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    if (!allRulesMet) {
      toast.error('Please meet all password requirements before saving.')
      return
    }

    if (!passwordMatches) {
      toast.error('New password and confirmation do not match.')
      return
    }

    setLoading(true)
    try {
      await apiClient.changeCompanyUserPasswordSecure({
        current_password: currentPassword,
        new_password: newPassword,
        confirm_password: confirmPassword,
      })

      updateUser({
        is_autogenerated_password: false,
        is_temporary_password: false,
        password_changed: true,
        must_change_password: false,
      } as any)
      setMustChangePassword(false)
      await refreshCurrentUser()

      toast.success('Password changed successfully.')
      setCurrentPassword('')
      setNewPassword('')
      setConfirmPassword('')
      // Clear session banner flag so it doesn't reappear
      sessionStorage.removeItem('pw_banner_dismissed')
      // Navigate to dashboard after a short delay
      setTimeout(() => navigate('/app/dashboard'), 800)
    } catch (error: any) {
      const msg = error.response?.data?.error || error.response?.data?.message || 'Failed to change password.'
      toast.error(msg)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-3xl font-semibold text-gray-900 dark:text-white">Change Password</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400 max-w-2xl">
            Update your account password securely. Your old password is required to verify identity.
          </p>
        </div>
        <button
          type="button"
          onClick={() => navigate('/app/dashboard')}
          className="inline-flex items-center gap-2 rounded-full border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm transition hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200 dark:hover:bg-gray-800"
        >
          <ShieldCheck className="h-4 w-4" /> Back to Dashboard
        </button>
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
        <div className="overflow-hidden rounded-3xl border border-gray-200 bg-white p-8 shadow-sm shadow-gray-200/40 dark:border-gray-800 dark:bg-gray-900 dark:shadow-black/10">
          <div className="flex items-center gap-3 mb-6">
            <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-600 text-white">
              <Lock className="h-5 w-5" />
            </div>
            <div>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Secure Password Update</h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">Protect your account with a strong, memorable password.</p>
            </div>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label className="text-sm font-medium text-gray-700 dark:text-gray-300">Current Password</label>
              <div className="relative mt-2">
                <input
                  type={showCurrent ? 'text' : 'password'}
                  value={currentPassword}
                  onChange={e => setCurrentPassword(e.target.value)}
                  required
                  autoComplete="current-password"
                  className="w-full rounded-2xl border border-gray-300 bg-white px-4 py-3 text-sm text-gray-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-200 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-100 dark:focus:border-blue-400 dark:focus:ring-blue-500/20"
                  placeholder="Enter current password"
                />
                <button
                  type="button"
                  onClick={() => setShowCurrent(prev => !prev)}
                  className="absolute inset-y-0 right-0 flex items-center pr-4 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
                >
                  {showCurrent ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
                </button>
              </div>
            </div>

            <div>
              <label className="text-sm font-medium text-gray-700 dark:text-gray-300">New Password</label>
              <div className="relative mt-2">
                <input
                  type={showNew ? 'text' : 'password'}
                  value={newPassword}
                  onChange={e => setNewPassword(e.target.value)}
                  required
                  autoComplete="new-password"
                  className="w-full rounded-2xl border border-gray-300 bg-white px-4 py-3 text-sm text-gray-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-200 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-100 dark:focus:border-blue-400 dark:focus:ring-blue-500/20"
                  placeholder="Enter new password"
                />
                <button
                  type="button"
                  onClick={() => setShowNew(prev => !prev)}
                  className="absolute inset-y-0 right-0 flex items-center pr-4 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
                >
                  {showNew ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
                </button>
              </div>
            </div>

            <div>
              <label className="text-sm font-medium text-gray-700 dark:text-gray-300">Confirm New Password</label>
              <div className="relative mt-2">
                <input
                  type={showConfirm ? 'text' : 'password'}
                  value={confirmPassword}
                  onChange={e => setConfirmPassword(e.target.value)}
                  required
                  autoComplete="new-password"
                  className="w-full rounded-2xl border border-gray-300 bg-white px-4 py-3 text-sm text-gray-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-200 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-100 dark:focus:border-blue-400 dark:focus:ring-blue-500/20"
                  placeholder="Confirm new password"
                />
                <button
                  type="button"
                  onClick={() => setShowConfirm(prev => !prev)}
                  className="absolute inset-y-0 right-0 flex items-center pr-4 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
                >
                  {showConfirm ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
                </button>
              </div>
            </div>

            <div className="rounded-3xl border border-gray-200 bg-gray-50 p-4 dark:border-gray-800 dark:bg-gray-950">
              <div className="flex items-center justify-between text-sm font-semibold text-gray-900 dark:text-white mb-3">
                <span>Password requirements</span>
                <span className={`rounded-full px-2 py-1 ${passwordStrength >= 4 ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/50 dark:text-emerald-300' : 'bg-gray-200 text-gray-700 dark:bg-gray-800 dark:text-gray-300'}`}>
                  {passwordStrength}/5
                </span>
              </div>
              <ul className="space-y-2 text-sm text-gray-600 dark:text-gray-400">
                {PASSWORD_RULES.map(rule => (
                  <li key={rule.label} className="flex items-center gap-2">
                    <span className={`h-2.5 w-2.5 rounded-full ${rule.test(newPassword) ? 'bg-green-500' : 'bg-gray-300 dark:bg-gray-700'}`} />
                    <span>{rule.label}</span>
                  </li>
                ))}
              </ul>
            </div>

            <button
              type="submit"
              disabled={loading || !currentPassword || !allRulesMet || !passwordMatches}
              className="inline-flex w-full items-center justify-center rounded-2xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {loading ? 'Saving...' : 'Save New Password'}
            </button>
          </form>
        </div>
      </div>
    </div>
  )
}

export default ChangePasswordPage
