import React, { useState } from 'react'
import { Eye, EyeOff, CheckCircle, ShieldCheck, Lock } from 'lucide-react'
import toast from 'react-hot-toast'
import { apiClient } from '../../lib/api'
import { useAuthStore } from '../../store/authStore'

interface Props {
  onSuccess: () => void
}

interface Rule { label: string; test: (p: string) => boolean }

const RULES: Rule[] = [
  { label: 'At least 8 characters',        test: p => p.length >= 8 },
  { label: 'One uppercase letter (A–Z)',    test: p => /[A-Z]/.test(p) },
  { label: 'One lowercase letter (a–z)',    test: p => /[a-z]/.test(p) },
  { label: 'One number (0–9)',              test: p => /\d/.test(p) },
  { label: 'One special character (@$!%…)', test: p => /[@$!%*?&#^()_\-+=]/.test(p) },
]

function strength(p: string): number {
  return RULES.filter(r => r.test(p)).length
}

const STRENGTH_LABELS = ['', 'Very Weak', 'Weak', 'Fair', 'Good', 'Strong']
const STRENGTH_COLORS = ['', 'bg-red-500', 'bg-orange-500', 'bg-yellow-500', 'bg-blue-500', 'bg-green-500']
const STRENGTH_TEXT   = ['', 'text-red-600', 'text-orange-600', 'text-yellow-600', 'text-blue-600', 'text-green-600']

const PostInductionPasswordChange: React.FC<Props> = ({ onSuccess }) => {
  const { updateUser } = useAuthStore()
  const [current, setCurrent]   = useState('')
  const [newPwd, setNewPwd]     = useState('')
  const [confirm, setConfirm]   = useState('')
  const [showCurrent, setShowCurrent] = useState(false)
  const [showNew, setShowNew]         = useState(false)
  const [showConfirm, setShowConfirm] = useState(false)
  const [loading, setLoading]   = useState(false)
  const [error, setError]       = useState<string | null>(null)

  const pwdStrength = strength(newPwd)
  const allRulesMet = pwdStrength === RULES.length
  const confirmMatch = newPwd === confirm && confirm.length > 0

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError(null)

    if (!allRulesMet) {
      setError('Password does not meet all requirements.')
      return
    }
    if (!confirmMatch) {
      setError('Passwords do not match.')
      return
    }

    setLoading(true)
    try {
      await apiClient.postInductionChangePassword({
        current_password: current,
        new_password: newPwd,
        confirm_password: confirm,
      })
      updateUser({
        must_change_password: false,
        is_temporary_password: false,
        is_autogenerated_password: false,
        password_changed: true,
        module_access_enabled: true,
        access_level: 'full_access',
        onboarding_completed: true,
      } as any)
      toast.success('Password updated successfully. Your account is now fully activated.')
      onSuccess()
    } catch (err: any) {
      const msg = err?.response?.data?.error || 'Failed to change password. Please try again.'
      setError(msg)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-gray-900/95 backdrop-blur-sm">
      <div className="w-full max-w-md mx-4">
        {/* Header */}
        <div className="text-center mb-6">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-blue-600 mb-4">
            <ShieldCheck className="h-8 w-8 text-white" />
          </div>
          <h1 className="text-2xl font-bold text-white">Password Change Required</h1>
          <p className="mt-2 text-sm text-gray-400">
            Induction training complete. Set a secure password to activate your account.
          </p>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl overflow-hidden">
          {/* Warning banner */}
          <div className="bg-amber-50 dark:bg-amber-900/30 border-b border-amber-200 dark:border-amber-700 px-5 py-3 flex items-center gap-2">
            <Lock className="h-4 w-4 text-amber-600 dark:text-amber-400 shrink-0" />
            <p className="text-xs text-amber-700 dark:text-amber-300 font-medium">
              All modules are locked until you set a new password.
            </p>
          </div>

          <form onSubmit={handleSubmit} className="p-6 space-y-4">
            {error && (
              <div className="p-3 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-700 rounded-lg text-sm text-red-700 dark:text-red-300">
                {error}
              </div>
            )}

            {/* Current password */}
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Current Temporary Password <span className="text-red-500">*</span>
              </label>
              <div className="relative">
                <input
                  type={showCurrent ? 'text' : 'password'}
                  value={current}
                  onChange={e => setCurrent(e.target.value)}
                  required
                  autoComplete="current-password"
                  className="w-full px-3 py-2 pr-10 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Enter your temporary password"
                />
                <button type="button" onClick={() => setShowCurrent(v => !v)}
                  className="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-600">
                  {showCurrent ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
            </div>

            {/* New password */}
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                New Password <span className="text-red-500">*</span>
              </label>
              <div className="relative">
                <input
                  type={showNew ? 'text' : 'password'}
                  value={newPwd}
                  onChange={e => setNewPwd(e.target.value)}
                  required
                  autoComplete="new-password"
                  className="w-full px-3 py-2 pr-10 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Create a strong password"
                />
                <button type="button" onClick={() => setShowNew(v => !v)}
                  className="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-600">
                  {showNew ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>

              {/* Strength bar */}
              {newPwd && (
                <div className="mt-2">
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs text-gray-500">Strength:</span>
                    <span className={`text-xs font-semibold ${STRENGTH_TEXT[pwdStrength]}`}>
                      {STRENGTH_LABELS[pwdStrength]}
                    </span>
                  </div>
                  <div className="flex gap-1">
                    {RULES.map((_, i) => (
                      <div key={i} className={`h-1.5 flex-1 rounded-full transition-all ${i < pwdStrength ? STRENGTH_COLORS[pwdStrength] : 'bg-gray-200 dark:bg-gray-600'}`} />
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Confirm password */}
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Confirm New Password <span className="text-red-500">*</span>
              </label>
              <div className="relative">
                <input
                  type={showConfirm ? 'text' : 'password'}
                  value={confirm}
                  onChange={e => setConfirm(e.target.value)}
                  required
                  autoComplete="new-password"
                  className={`w-full px-3 py-2 pr-10 border rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 ${
                    confirm && !confirmMatch
                      ? 'border-red-400 focus:ring-red-400'
                      : confirmMatch
                      ? 'border-green-400 focus:ring-green-400'
                      : 'border-gray-300 dark:border-gray-600 focus:ring-blue-500'
                  }`}
                  placeholder="Re-enter your new password"
                />
                <button type="button" onClick={() => setShowConfirm(v => !v)}
                  className="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-600">
                  {showConfirm ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
              {confirm && !confirmMatch && (
                <p className="mt-1 text-xs text-red-600">Passwords do not match</p>
              )}
            </div>

            {/* Rules checklist */}
            <div className="bg-gray-50 dark:bg-gray-700/50 rounded-xl p-4">
              <p className="text-xs font-semibold text-gray-700 dark:text-gray-300 mb-2">Password Requirements:</p>
              <ul className="space-y-1">
                {RULES.map(rule => (
                  <li key={rule.label} className="flex items-center gap-2 text-xs">
                    <CheckCircle className={`h-3.5 w-3.5 shrink-0 ${rule.test(newPwd) ? 'text-green-500' : 'text-gray-300 dark:text-gray-600'}`} />
                    <span className={rule.test(newPwd) ? 'text-green-700 dark:text-green-400' : 'text-gray-500 dark:text-gray-400'}>
                      {rule.label}
                    </span>
                  </li>
                ))}
              </ul>
            </div>

            <button
              type="submit"
              disabled={loading || !allRulesMet || !confirmMatch || !current}
              className="w-full py-2.5 px-4 bg-blue-600 hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed text-white text-sm font-semibold rounded-lg transition-colors"
            >
              {loading ? 'Updating Password…' : 'Set New Password & Activate Account'}
            </button>
          </form>
        </div>
      </div>
    </div>
  )
}

export default PostInductionPasswordChange
