"""
Profile Management API
- Admin (role_type=admin, companyuser): create users, list users, approve/reject
- User (role_type=user, companyuser): submit profile form on first login
"""
import secrets
import string

from django.utils import timezone
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from authentication.models import User, UserType
from authentication.tenant_utils import get_tenant_id_for_filtering


def _generate_password(length=12):
    alphabet = string.ascii_letters + string.digits + "!@#$%"
    return ''.join(secrets.choice(alphabet) for _ in range(length))


def _is_company_admin(user):
    return user.user_type == UserType.COMPANYUSER and getattr(user, 'role_type', 'admin') == 'admin'


# ─── Admin: Create User ───────────────────────────────────────────────────────

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def create_user(request):
    """Admin creates a user under their company_type."""
    if not _is_company_admin(request.user):
        return Response({'error': 'Only company admins can create users.'}, status=403)

    email = request.data.get('email', '').strip()
    if not email:
        return Response({'error': 'Email is required.'}, status=400)

    if User.objects.filter(email=email).exists():
        return Response({'error': 'Email already in use.'}, status=400)

    password = _generate_password()
    company_type = getattr(request.user, 'company_type', None)
    tenant_id = get_tenant_id_for_filtering(request.user)

    user = User.objects.create_user(
        email=email,
        password=password,
        user_type=UserType.COMPANYUSER,
        role_type='user',
        company_type=company_type,
        company_id=tenant_id,
        created_by=request.user,
        is_first_login=True,
        approval_status='pending',
        is_autogenerated_password=True,
    )

    return Response({
        'id': user.id,
        'email': user.email,
        'password': password,
        'company_type': company_type,
        'approval_status': user.approval_status,
        'is_first_login': user.is_first_login,
    }, status=201)


# ─── Admin: List Users ────────────────────────────────────────────────────────

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def list_managed_users(request):
    """List users created by this admin (scoped to company_type + tenant)."""
    if not _is_company_admin(request.user):
        return Response({'error': 'Forbidden'}, status=403)

    company_type = getattr(request.user, 'company_type', None)
    tenant_id = get_tenant_id_for_filtering(request.user)

    qs = User.objects.filter(
        role_type='user',
        company_type=company_type,
        company_id=tenant_id,
    ).order_by('-created_at')

    data = [{
        'id': u.id,
        'email': u.email,
        'name': u.name or '',
        'phone': u.phone_number or '',
        'department': u.department or '',
        'designation': u.designation or '',
        'approval_status': u.approval_status,
        'is_first_login': u.is_first_login,
        'is_active': u.is_active,
        'created_at': u.created_at.isoformat(),
    } for u in qs]

    return Response({'results': data})


# ─── Admin: Pending Approvals ─────────────────────────────────────────────────

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def pending_approvals(request):
    """List users who submitted profile form and are awaiting approval."""
    if not _is_company_admin(request.user):
        return Response({'error': 'Forbidden'}, status=403)

    company_type = getattr(request.user, 'company_type', None)
    tenant_id = get_tenant_id_for_filtering(request.user)

    qs = User.objects.filter(
        role_type='user',
        company_type=company_type,
        company_id=tenant_id,
        approval_status='pending',
        is_first_login=False,  # profile already submitted
    ).order_by('-created_at')

    data = [{
        'id': u.id,
        'email': u.email,
        'name': u.name or '',
        'phone': u.phone_number or '',
        'department': u.department or '',
        'designation': u.designation or '',
        'created_at': u.created_at.isoformat(),
    } for u in qs]

    return Response({'results': data})


# ─── Admin: Approve ───────────────────────────────────────────────────────────

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def approve_user(request, user_id):
    if not _is_company_admin(request.user):
        return Response({'error': 'Forbidden'}, status=403)

    company_type = getattr(request.user, 'company_type', None)
    tenant_id = get_tenant_id_for_filtering(request.user)

    try:
        user = User.objects.get(id=user_id, role_type='user', company_type=company_type, company_id=tenant_id)
    except User.DoesNotExist:
        return Response({'error': 'User not found.'}, status=404)

    user.approval_status = 'approved'
    user.save(update_fields=['approval_status'])
    return Response({'message': 'User approved.', 'approval_status': 'approved'})


# ─── Admin: Reject ────────────────────────────────────────────────────────────

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def reject_user(request, user_id):
    if not _is_company_admin(request.user):
        return Response({'error': 'Forbidden'}, status=403)

    company_type = getattr(request.user, 'company_type', None)
    tenant_id = get_tenant_id_for_filtering(request.user)

    try:
        user = User.objects.get(id=user_id, role_type='user', company_type=company_type, company_id=tenant_id)
    except User.DoesNotExist:
        return Response({'error': 'User not found.'}, status=404)

    user.approval_status = 'rejected'
    user.save(update_fields=['approval_status'])
    return Response({'message': 'User rejected.', 'approval_status': 'rejected'})


# ─── User: Submit Profile Form ────────────────────────────────────────────────

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def complete_profile(request):
    """User submits profile form on first login. Sets approval_status=pending."""
    user = request.user

    if getattr(user, 'role_type', 'admin') != 'user':
        return Response({'error': 'Only regular users can complete profile.'}, status=403)

    if not user.is_first_login:
        return Response({'error': 'Profile already completed.'}, status=400)

    name = request.data.get('name', '').strip()
    phone = request.data.get('phone', '').strip()
    department = request.data.get('department', '').strip()
    designation = request.data.get('designation', '').strip()

    if not all([name, phone, department, designation]):
        return Response({'error': 'name, phone, department, designation are required.'}, status=400)

    user.name = name
    user.phone_number = phone
    user.department = department
    user.designation = designation
    user.is_first_login = False
    # approval_status stays 'pending' until admin approves
    user.save(update_fields=['name', 'phone_number', 'department', 'designation', 'is_first_login'])

    return Response({
        'message': 'Profile submitted. Waiting for admin approval.',
        'approval_status': user.approval_status,
    })
