"""
Athens Multi-Tenant Control Models

This module defines the tenant control plane for Athens multi-tenant architecture.
The athens_tenant_id is the ONLY isolation key used throughout the system.
"""

import uuid
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import logging

logger = logging.getLogger(__name__)


class AthensTenant(models.Model):
    """
    Central tenant control table for Athens multi-tenant architecture.
    
    This table controls:
    - Module enable/disable per tenant
    - Menu enable/disable per tenant
    - Tenant activation/deactivation
    - Master admin assignment
    """
    
    # Primary tenant identifier - generated by SAP
    id = models.UUIDField(
        primary_key=True,
        verbose_name=_('Athens Tenant ID'),
        help_text=_('Unique tenant identifier generated by SAP')
    )
    
    # Optional reference to legacy company_id (for business context only)
    company_id = models.UUIDField(
        null=True,
        blank=True,
        verbose_name=_('Company ID'),
        help_text=_('Optional reference to legacy company identifier')
    )
    
    # Master admin for this tenant
    master_admin_id = models.UUIDField(
        verbose_name=_('Master Admin ID'),
        help_text=_('Master admin user ID from SAP')
    )
    
    # Module control
    enabled_modules = models.JSONField(
        default=list,
        verbose_name=_('Enabled Modules'),
        help_text=_('List of enabled modules for this tenant')
    )
    
    # Menu control
    enabled_menus = models.JSONField(
        default=list,
        verbose_name=_('Enabled Menus'),
        help_text=_('List of enabled menus for this tenant')
    )
    
    # Tenant status
    is_active = models.BooleanField(
        default=True,
        verbose_name=_('Is Active'),
        help_text=_('Whether this tenant is active and can access Athens')
    )
    
    # Metadata
    tenant_name = models.CharField(
        max_length=255,
        blank=True,
        verbose_name=_('Tenant Name'),
        help_text=_('Human-readable tenant name for identification')
    )
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = _('Athens Tenant')
        verbose_name_plural = _('Athens Tenants')
        db_table = 'athens_tenant'
        indexes = [
            models.Index(fields=['master_admin_id']),
            models.Index(fields=['is_active']),
        ]
    
    def __str__(self):
        return f"Tenant {self.id} - {self.tenant_name or 'Unnamed'}"
    
    def clean(self):
        """Validate tenant data"""
        super().clean()
        
        # Validate enabled_modules format
        if not isinstance(self.enabled_modules, list):
            raise ValidationError({'enabled_modules': 'Must be a list'})
        
        # Validate enabled_menus format
        if not isinstance(self.enabled_menus, list):
            raise ValidationError({'enabled_menus': 'Must be a list'})
    
    def is_module_enabled(self, module_name):
        """Check if a module is enabled for this tenant"""
        return module_name in self.enabled_modules
    
    def is_menu_enabled(self, menu_name):
        """Check if a menu is enabled for this tenant"""
        return menu_name in self.enabled_menus
    
    def enable_module(self, module_name):
        """Enable a module for this tenant"""
        if module_name not in self.enabled_modules:
            self.enabled_modules.append(module_name)
            self.save(update_fields=['enabled_modules', 'updated_at'])
    
    def disable_module(self, module_name):
        """Disable a module for this tenant"""
        if module_name in self.enabled_modules:
            self.enabled_modules.remove(module_name)
            self.save(update_fields=['enabled_modules', 'updated_at'])
    
    def enable_menu(self, menu_name):
        """Enable a menu for this tenant"""
        if menu_name not in self.enabled_menus:
            self.enabled_menus.append(menu_name)
            self.save(update_fields=['enabled_menus', 'updated_at'])
    
    def disable_menu(self, menu_name):
        """Disable a menu for this tenant"""
        if menu_name in self.enabled_menus:
            self.enabled_menus.remove(menu_name)
            self.save(update_fields=['enabled_menus', 'updated_at'])


class TenantAuditLog(models.Model):
    """
    Audit log for tenant configuration changes.
    
    SECURITY: This model is APPEND-ONLY for audit integrity.
    Updates and deletes are blocked at the ORM level.
    """
    
    ACTION_CHOICES = [
        ('created', _('Tenant Created')),
        ('activated', _('Tenant Activated')),
        ('deactivated', _('Tenant Deactivated')),
        ('module_enabled', _('Module Enabled')),
        ('module_disabled', _('Module Disabled')),
        ('menu_enabled', _('Menu Enabled')),
        ('menu_disabled', _('Menu Disabled')),
        ('master_admin_changed', _('Master Admin Changed')),
        ('updated', _('Tenant Updated')),
    ]
    
    tenant = models.ForeignKey(
        AthensTenant,
        on_delete=models.CASCADE,
        related_name='audit_logs'
    )
    
    action = models.CharField(
        max_length=30,
        choices=ACTION_CHOICES,
        verbose_name=_('Action')
    )
    
    description = models.TextField(
        verbose_name=_('Description'),
        help_text=_('Detailed description of the action')
    )
    
    # Change tracking
    previous_value = models.JSONField(
        null=True,
        blank=True,
        verbose_name=_('Previous Value'),
        help_text=_('Previous value before change')
    )
    
    new_value = models.JSONField(
        null=True,
        blank=True,
        verbose_name=_('New Value'),
        help_text=_('New value after change')
    )
    
    # Actor information
    performed_by = models.UUIDField(
        null=True,
        blank=True,
        verbose_name=_('Performed By'),
        help_text=_('User ID who performed the action')
    )
    
    # Request context
    ip_address = models.GenericIPAddressField(
        null=True,
        blank=True,
        verbose_name=_('IP Address')
    )
    
    user_agent = models.TextField(
        blank=True,
        verbose_name=_('User Agent')
    )
    
    timestamp = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = _('Tenant Audit Log')
        verbose_name_plural = _('Tenant Audit Logs')
        db_table = 'tenant_audit_log'
        ordering = ['-timestamp']
        indexes = [
            models.Index(fields=['tenant', '-timestamp']),
            models.Index(fields=['action']),
        ]
    
    def __str__(self):
        return f"{self.tenant.id} - {self.get_action_display()} at {self.timestamp}"
    
    def save(self, *args, **kwargs):
        """Override save to prevent updates after creation"""
        if self.pk is not None:
            raise ValidationError("Audit logs are immutable and cannot be updated")
        super().save(*args, **kwargs)
    
    def delete(self, *args, **kwargs):
        """Override delete to prevent deletion"""
        raise ValidationError("Audit logs are immutable and cannot be deleted")


# Default module and menu configurations
DEFAULT_MODULES = [
    'authentication',
    'worker',
    'tbt',
    'inductiontraining',
    'jobtraining',
    'mom',
    'safetyobservation',
    'ptw',
    'manpower',
    'incidentmanagement',
    'inspection',
    'permissions',
    'system',
    'environment',
    'quality',
    'voice_translator',
]

DEFAULT_MENUS = [
    'dashboard',
    'workers',
    'training',
    'safety',
    'incidents',
    'permits',
    'inspections',
    'reports',
    'settings',
]