# Generated by Django 5.2.5 on 2025-08-28 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('worker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('conducted_by', models.CharField(max_length=255, verbose_name='Conducted By')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_job_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_trainings', to='authentication.project')),
            ],
            options={
                'verbose_name': 'Job Training',
                'verbose_name_plural': 'Job Trainings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JobTrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=20, verbose_name='Status')),
                ('attendance_photo', models.TextField(blank=True, verbose_name='Attendance Photo')),
                ('match_score', models.FloatField(default=0, verbose_name='Match Score')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='jobtraining.jobtraining')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_training_attendances', to='worker.worker')),
            ],
            options={
                'verbose_name': 'Job Training Attendance',
                'verbose_name_plural': 'Job Training Attendances',
                'unique_together': {('job_training', 'worker')},
            },
        ),
    ]
