# Generated by Django 5.2.1 on 2025-12-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtraining', '0001_initial'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobtrainingattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobtrainingattendance',
            name='participant_type',
            field=models.CharField(choices=[('worker', 'Worker'), ('user', 'User')], default='worker', max_length=20, verbose_name='Participant Type'),
        ),
        migrations.AddField(
            model_name='jobtrainingattendance',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='jobtrainingattendance',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='jobtrainingattendance',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_training_attendances', to='worker.worker'),
        ),
    ]
