# Generated by Django 5.2.14 on 2026-05-13 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLFeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('entity_type', models.CharField(choices=[('worker', 'Worker'), ('contractor', 'Contractor'), ('permit', 'Permit'), ('project', 'Project'), ('location', 'Location')], max_length=20)),
                ('entity_id', models.IntegerField(db_index=True)),
                ('features', models.JSONField(default=dict)),
                ('feature_version', models.CharField(default='1.0', max_length=20)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ml_feature_snapshots',
                'indexes': [models.Index(fields=['tenant_id', 'entity_type'], name='ml_feature__tenant__4d7b76_idx')],
                'unique_together': {('tenant_id', 'entity_type', 'entity_id')},
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('incident_predictor', 'Incident Predictor'), ('worker_risk', 'Worker Risk Scorer'), ('contractor_risk', 'Contractor Risk Scorer'), ('risk_matrix', 'Smart Risk Matrix'), ('anomaly_detector', 'Anomaly Detector'), ('fatigue_predictor', 'Fatigue Predictor'), ('permit_risk', 'Permit Risk Scorer'), ('safety_forecaster', 'Safety Forecaster')], max_length=30)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('status', models.CharField(choices=[('training', 'Training'), ('ready', 'Ready'), ('deployed', 'Deployed'), ('deprecated', 'Deprecated'), ('failed', 'Failed')], default='training', max_length=15)),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, help_text='null = global model, int = tenant-specific', null=True)),
                ('model_path', models.CharField(blank=True, max_length=500)),
                ('training_samples', models.IntegerField(default=0)),
                ('feature_names', models.JSONField(default=list)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('roc_auc', models.FloatField(blank=True, null=True)),
                ('baseline_distribution', models.JSONField(blank=True, default=dict)),
                ('drift_threshold', models.FloatField(default=0.1)),
                ('last_drift_check', models.DateTimeField(blank=True, null=True)),
                ('drift_detected', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ml_models',
                'indexes': [models.Index(fields=['model_type', 'status'], name='ml_models_model_t_426c2a_idx'), models.Index(fields=['tenant_id', 'model_type'], name='ml_models_tenant__a1c9d2_idx')],
                'unique_together': {('model_type', 'version', 'tenant_id')},
            },
        ),
        migrations.CreateModel(
            name='MLTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('model_type', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=30)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ml_telemetry',
                'indexes': [models.Index(fields=['model_type', '-created_at'], name='ml_telemetr_model_t_40b19f_idx'), models.Index(fields=['tenant_id', '-created_at'], name='ml_telemetr_tenant__39cd88_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLAnomalyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('anomaly_type', models.CharField(choices=[('permit_anomaly', 'Permit Anomaly'), ('attendance_spike', 'Attendance Spike'), ('unsafe_act_cluster', 'Unsafe Act Cluster'), ('contractor_behavior', 'Contractor Behavior'), ('incident_pattern', 'Incident Pattern'), ('work_combination', 'Unsafe Work Combination'), ('overtime_abuse', 'Overtime Abuse')], max_length=30)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('anomaly_score', models.FloatField()),
                ('severity', models.CharField(default='medium', max_length=10)),
                ('description', models.TextField()),
                ('feature_contributions', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_anomaly_records',
                'indexes': [models.Index(fields=['tenant_id', 'anomaly_type', '-created_at'], name='ml_anomaly__tenant__41c59d_idx'), models.Index(fields=['tenant_id', 'status'], name='ml_anomaly__tenant__a3359c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('model_type', models.CharField(db_index=True, max_length=30)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('feature_vector', models.JSONField(default=dict)),
                ('prediction_label', models.CharField(blank=True, max_length=50)),
                ('prediction_score', models.FloatField()),
                ('confidence', models.FloatField(default=0.0)),
                ('explanation', models.JSONField(default=dict)),
                ('actual_outcome', models.CharField(blank=True, max_length=50)),
                ('feedback_received', models.BooleanField(default=False)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('used_fallback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='ml.mlmodel')),
            ],
            options={
                'db_table': 'ml_predictions',
                'indexes': [models.Index(fields=['tenant_id', 'model_type', '-created_at'], name='ml_predicti_tenant__88840f_idx'), models.Index(fields=['tenant_id', 'entity_type', 'entity_id'], name='ml_predicti_tenant__072abc_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLTrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=30)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=15)),
                ('config', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('samples_used', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml.mlmodel')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_training_jobs',
                'indexes': [models.Index(fields=['model_type', 'status', '-created_at'], name='ml_training_model_t_41599b_idx')],
            },
        ),
    ]
