import pytest
from django.urls import reverse
from rest_framework import status
from authentication.models import User, Project, SecurityLog, UserType
from control_plane.models import Tenant


@pytest.mark.django_db
def test_create_project_admin_audit_log(api_client, master_admin_user, tenant):
    """Test that audit log is created when project admin is created"""
    
    # Create a project
    project = Project.objects.create(
        projectName="Test Project",
        projectCategory="construction",
        capacity="100",
        location="Test Location",
        nearestPoliceStation="Test Police",
        nearestPoliceStationContact="123",
        nearestHospital="Test Hospital",
        nearestHospitalContact="456",
        commencementDate="2025-01-01",
        deadlineDate="2025-12-31",
        athens_tenant_id=tenant.id
    )
    
    # Login as master admin
    api_client.force_authenticate(user=master_admin_user)
    
    # Count existing audit logs
    initial_count = SecurityLog.objects.count()
    
    # Create project admin
    url = reverse('masteradmin:create-project-admin')
    data = {
        'project_id': project.id,
        'admin_type': 'client',
        'username': 'test_client_admin',
        'company_name': 'Test Company',
        'registered_address': '123 Test Street'
    }
    
    response = api_client.post(url, data, format='json')
    
    # Verify response
    assert response.status_code == status.HTTP_201_CREATED
    assert 'password' in response.data
    
    # Verify audit log created
    assert SecurityLog.objects.count() == initial_count + 1
    
    # Get the audit log
    audit_log = SecurityLog.objects.latest('created_at')
    
    # Verify audit log details
    assert audit_log.event_type == SecurityLog.EventType.MASTER_CREATED
    assert audit_log.user == master_admin_user
    assert audit_log.metadata['event'] == 'masteradmin.create_project_admin'
    assert audit_log.metadata['source'] == 'web'
    assert audit_log.metadata['actor_user_id'] == master_admin_user.id
    assert audit_log.metadata['project_id'] == project.id
    assert audit_log.metadata['admin_type'] == 'client'
    assert audit_log.metadata['company_name'] == 'Test Company'
    assert audit_log.metadata['created_username'] == 'test_client_admin'
    
    # CRITICAL: Verify password is NOT logged
    assert 'password' not in audit_log.metadata
    assert 'generated_password' not in audit_log.metadata
    
    # Verify created user
    created_user = User.objects.get(username='test_client_admin')
    assert created_user.admin_type == 'client'
    assert created_user.company_name == 'Test Company'
    assert created_user.is_autogenerated_password is True
    assert created_user.is_password_reset_required is True


@pytest.mark.django_db
def test_create_project_admin_audit_log_no_password_leak(api_client, master_admin_user, tenant):
    """Test that password is NEVER logged in audit trail"""
    
    project = Project.objects.create(
        projectName="Test Project 2",
        projectCategory="construction",
        capacity="100",
        location="Test",
        nearestPoliceStation="Test",
        nearestPoliceStationContact="123",
        nearestHospital="Test",
        nearestHospitalContact="456",
        commencementDate="2025-01-01",
        deadlineDate="2025-12-31",
        athens_tenant_id=tenant.id
    )
    
    api_client.force_authenticate(user=master_admin_user)
    
    url = reverse('masteradmin:create-project-admin')
    data = {
        'project_id': project.id,
        'admin_type': 'epc',
        'username': 'test_epc_admin',
        'company_name': 'EPC Company',
        'registered_address': '456 EPC Street'
    }
    
    response = api_client.post(url, data, format='json')
    assert response.status_code == status.HTTP_201_CREATED
    
    # Get password from response
    generated_password = response.data['password']
    
    # Verify password is in response
    assert len(generated_password) == 16
    
    # Get all audit logs
    audit_logs = SecurityLog.objects.all()
    
    # Verify password is NOT in any audit log
    for log in audit_logs:
        metadata_str = str(log.metadata)
        assert generated_password not in metadata_str
        assert 'password' not in log.metadata
