import { apiClient } from '../lib/api'

export interface ManagedUser {
  id: number
  username: string
  email: string
  name: string
  surname: string
  phone_number: string
  department: string
  designation: string
  employee_id: string
  emergency_contact: string
  blood_group: string
  address: string
  safety_experience: string
  skills: string
  language_preference: string
  company_type: string
  approval_status: 'pending' | 'approved' | 'rejected'
  status: string
  profile_completed: boolean
  profile_submitted_at: string | null
  approved_at: string | null
  approved_by: string | null
  induction_attended: boolean
  induction_attended_at: string | null
  is_active: boolean
  created_at: string
  profile_photo: string | null
  // Password status flags
  is_temporary_password: boolean
  password_changed: boolean
  must_change_password: boolean
  is_autogenerated_password: boolean
}

const BASE = '/api/auth/projectadmin'

export const profileManagementApi = {
  // Admin: user management
  createUser: (data: { username: string; email?: string; name?: string }) =>
    apiClient.post(`${BASE}/users/`, data),

  listUsers: () =>
    apiClient.get<ManagedUser[]>(`${BASE}/users/`),

  getUserStats: () =>
    apiClient.get(`${BASE}/users/stats/`),

  deleteUser: (userId: number) =>
    apiClient.delete(`${BASE}/users/${userId}/delete/`),

  resetUserPassword: (userId: number) =>
    apiClient.post(`${BASE}/users/${userId}/reset-password/`, {}),

  suspendUser: (userId: number) =>
    apiClient.post(`${BASE}/users/${userId}/suspend/`, {}),

  activateUser: (userId: number) =>
    apiClient.post(`${BASE}/users/${userId}/activate/`, {}),

  // Admin: approval workflow
  listPendingApprovals: () =>
    apiClient.get<ManagedUser[]>(`${BASE}/approvals/`),

  approveUser: (userId: number) =>
    apiClient.post(`${BASE}/approvals/${userId}/approve/`, {}),

  rejectUser: (userId: number, reason?: string) =>
    apiClient.post(`${BASE}/approvals/${userId}/reject/`, { reason }),

  // Admin: induction attendance
  markInductionAttendance: (userId: number) =>
    apiClient.post(`${BASE}/users/${userId}/mark-induction/`, {}),

  // User: profile completion
  completeProfile: (data: FormData) =>
    apiClient.post(`${BASE}/profile/complete/`, data, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),

  getMyStatus: () =>
    apiClient.get(`${BASE}/status/`),
}
