# Generated by Django 5.2.5 on 2025-08-28 02:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$')])),
                ('surname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$')])),
                ('father_or_spouse_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$')])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('education_level', models.CharField(choices=[('No Formal Education', 'No Formal Education'), ('High School Diploma / Equivalent', 'High School Diploma / Equivalent'), ('Vocational Training / Certification', 'Vocational Training / Certification'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctorate / PhD', 'Doctorate / PhD'), ('Other', 'Other')], max_length=100)),
                ('education_other', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_joining', models.DateField()),
                ('designation', models.CharField(choices=[('Production Manager', 'Production Manager'), ('Production Supervisor / Shift In-charge', 'Production Supervisor / Shift In-charge'), ('Line Leader / Assembly Line Leader', 'Line Leader / Assembly Line Leader'), ('Machine Operator', 'Machine Operator'), ('Assembly Technician / Production Helper', 'Assembly Technician / Production Helper'), ('Batch Maker / Process Operator', 'Batch Maker / Process Operator'), ('Maintenance Manager', 'Maintenance Manager'), ('Mechanical Maintenance Engineer / Technician', 'Mechanical Maintenance Engineer / Technician'), ('Electrical Maintenance Engineer / Technician', 'Electrical Maintenance Engineer / Technician'), ('Utility Maintenance Technician', 'Utility Maintenance Technician'), ('Preventive Maintenance Planner', 'Preventive Maintenance Planner'), ('QA/QC Manager', 'QA/QC Manager'), ('QA/QC Engineer', 'QA/QC Engineer'), ('Quality Inspector', 'Quality Inspector'), ('Lab Analyst / QC Chemist / Microbiologist', 'Lab Analyst / QC Chemist / Microbiologist'), ('Calibration Technician', 'Calibration Technician'), ('EHS Manager / HSE Lead', 'EHS Manager / HSE Lead'), ('Safety Officer', 'Safety Officer'), ('Environmental Engineer / Compliance Officer', 'Environmental Engineer / Compliance Officer'), ('Fire Safety Officer / Fire & Emergency Coordinator', 'Fire Safety Officer / Fire & Emergency Coordinator'), ('Chemical Safety Officer / Waste Management Officer', 'Chemical Safety Officer / Waste Management Officer'), ('PPE Compliance Checker', 'PPE Compliance Checker'), ('Utility Manager', 'Utility Manager'), ('Boiler Operator', 'Boiler Operator'), ('Chiller / Compressor / HVAC Technician', 'Chiller / Compressor / HVAC Technician'), ('Water Treatment Plant (WTP/ETP) Operator', 'Water Treatment Plant (WTP/ETP) Operator'), ('Electrical Technician (Facility)', 'Electrical Technician (Facility)'), ('R&D Manager', 'R&D Manager'), ('Design Engineer / CAD Engineer', 'Design Engineer / CAD Engineer'), ('Product Development Engineer', 'Product Development Engineer'), ('Testing / Prototype Engineer', 'Testing / Prototype Engineer'), ('Firmware / Hardware Engineer (Electronics)', 'Firmware / Hardware Engineer (Electronics)'), ('Packaging Manager', 'Packaging Manager'), ('Packing Supervisor', 'Packing Supervisor'), ('Machine Operator – Packing', 'Machine Operator – Packing'), ('Labeling & Coding Technician', 'Labeling & Coding Technician'), ('Artwork Coordinator', 'Artwork Coordinator'), ('Supply Chain Manager', 'Supply Chain Manager'), ('Logistics Coordinator', 'Logistics Coordinator'), ('Store Keeper / Inventory Controller', 'Store Keeper / Inventory Controller'), ('Warehouse In-charge / Assistant', 'Warehouse In-charge / Assistant'), ('Material Handler / Forklift Operator', 'Material Handler / Forklift Operator'), ('Fire Safety In-charge', 'Fire Safety In-charge'), ('Emergency Response Technician / Fireman', 'Emergency Response Technician / Fireman'), ('Fire Drill / Rescue Coordinator', 'Fire Drill / Rescue Coordinator'), ('First Aider', 'First Aider'), ('Extinguisher / Alarm Technician', 'Extinguisher / Alarm Technician'), ('HR Manager / HR Executive', 'HR Manager / HR Executive'), ('Admin Officer', 'Admin Officer'), ('Training & Development Coordinator', 'Training & Development Coordinator'), ('Time Office In-charge / Attendance Clerk', 'Time Office In-charge / Attendance Clerk'), ('Worker Welfare / Compliance Officer', 'Worker Welfare / Compliance Officer')], max_length=200)),
                ('category', models.CharField(choices=[('Highly Skilled', 'Highly Skilled'), ('Skilled', 'Skilled'), ('Semi Skilled', 'Semi Skilled'), ('Unskilled', 'Unskilled')], max_length=20)),
                ('employment_type', models.CharField(choices=[('temporary', 'Temporary'), ('permanent', 'Permanent')], default='temporary', max_length=20)),
                ('department', models.CharField(choices=[('Production / Manufacturing', 'Production / Manufacturing'), ('Maintenance', 'Maintenance'), ('Quality Control / Quality Assurance (QC/QA)', 'Quality Control / Quality Assurance (QC/QA)'), ('EHS (Environment, Health & Safety)', 'EHS (Environment, Health & Safety)'), ('Utilities & Facility Management', 'Utilities & Facility Management'), ('Research & Development / Design & Engineering', 'Research & Development / Design & Engineering'), ('Packaging & Labeling', 'Packaging & Labeling'), ('Logistics / Stores / Supply Chain', 'Logistics / Stores / Supply Chain'), ('Fire Safety & Emergency Response', 'Fire Safety & Emergency Response'), ('HR & Administration', 'HR & Administration')], max_length=200)),
                ('phone_number', models.CharField(help_text='10-digit Indian mobile number starting with 6, 7, 8, or 9', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', message='Enter a valid 10-digit Indian mobile number')])),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('aadhaar', models.CharField(help_text='12-digit Aadhaar number (required and unique)', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', message='Aadhaar must be exactly 12 digits')])),
                ('pan', models.CharField(blank=True, help_text='10-character PAN number (optional but unique if provided)', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]{1}$', message='Invalid PAN format (e.g., ABCDE1234F)')])),
                ('uan', models.CharField(blank=True, help_text='12-digit UAN number (optional but unique if provided)', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', message='UAN must be exactly 12 digits')])),
                ('esic_ip', models.CharField(blank=True, help_text='ESIC IP number (optional but unique if provided)', max_length=50, null=True, unique=True)),
                ('lwf', models.CharField(blank=True, help_text='Labour Welfare Fund number (optional)', max_length=50, null=True)),
                ('mark_of_identification', models.CharField(help_text='Physical identification mark (e.g., mole on right cheek, scar on left hand)', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='worker_photos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('employment_status', models.CharField(choices=[('initiated', 'Initiated'), ('deployed', 'Deployed'), ('terminated', 'Terminated'), ('site_transferred', 'Site Transferred')], default='initiated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_workers', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='authentication.project')),
            ],
            options={
                'permissions': [('view_all_workers', 'Can view all workers'), ('manage_workers', 'Can manage workers')],
            },
        ),
    ]
