# Generated by Django 5.2.11 on 2026-02-23 09:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyManpowerSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('project_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('total_workers', models.PositiveIntegerField(default=0)),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('total_overtime', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('half_day_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ergon_daily_manpower_summary',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['athens_tenant_id', 'date'], name='ergon_daily_athens__89320c_idx'), models.Index(fields=['athens_tenant_id', 'project_id', 'date'], name='ergon_daily_athens__a586d6_idx')],
                'unique_together': {('athens_tenant_id', 'project_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#1890ff', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ergon_work_type',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['athens_tenant_id', 'is_active'], name='ergon_work__athens__bfcfa9_idx')],
                'unique_together': {('athens_tenant_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ManpowerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('project_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shift', models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('general', 'General')], default='general', max_length=10)),
                ('hours_worked', models.DecimalField(decimal_places=1, default=8.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('overtime_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day')], default='present', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_entries', to='ergon_manpower.worktype')),
            ],
            options={
                'db_table': 'ergon_manpower_entry',
                'ordering': ['-date', 'category', 'gender'],
                'indexes': [models.Index(fields=['athens_tenant_id', 'date'], name='ergon_manpo_athens__29cc1b_idx'), models.Index(fields=['athens_tenant_id', 'project_id', 'date'], name='ergon_manpo_athens__7146bf_idx'), models.Index(fields=['created_by_id'], name='ergon_manpo_created_c6e4a7_idx')],
            },
        ),
    ]
