# Generated by Django 5.2.14 on 2026-05-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_inspectiontemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(choices=[('quality', 'Quality Inspection'), ('civil', 'Civil Inspection'), ('electrical', 'Electrical Inspection')], max_length=20),
        ),
    ]
