# Generated by Django 5.2.14 on 2026-05-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_management', '0003_training_assigned_user_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', help_text='online = user self-completes; offline = admin marks attendance', max_length=10),
        ),
        migrations.AlterField(
            model_name='trainingattendance',
            name='attendance_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
