# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_management', '0004_alter_training_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.CharField(
                choices=[
                    ('induction', 'Induction Training'),
                    ('induction_training', 'Induction Training'),
                    ('safety', 'Safety Training'),
                    ('safety_training', 'Safety Training'),
                    ('ptw_training', 'PTW Training'),
                    ('toolbox_training', 'Toolbox Talk'),
                    ('inspection_training', 'Inspection Training'),
                    ('technical', 'Technical Training'),
                    ('job_training', 'Job Training'),
                    ('compliance', 'Compliance Training'),
                    ('other', 'Other'),
                ],
                max_length=20,
            ),
        ),
    ]
