# Generated by Django 5.2.14 on 2026-05-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_management', '0011_training_owner_company_tenant_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingattendance',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='trainingattendance',
            name='otp_expires_at',
        ),
    ]
