# Generated by Django 5.2.11 on 2026-02-23 15:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ergon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseoutChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('extreme', 'Extreme')], max_length=10, null=True)),
                ('items', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ptw_closeout_checklist_template',
                'ordering': ['permit_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('hot_work', 'Hot Work'), ('confined_space', 'Confined Space'), ('electrical', 'Electrical Work'), ('height', 'Work at Height'), ('excavation', 'Excavation'), ('cold_work', 'Cold Work')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#1890ff', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('extreme', 'Extreme')], default='low', max_length=10)),
                ('validity_hours', models.PositiveIntegerField(default=24)),
                ('requires_gas_testing', models.BooleanField(default=False)),
                ('requires_isolation', models.BooleanField(default=False)),
                ('mandatory_ppe', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ptw_permit_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IsolationPointLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('point_code', models.CharField(max_length=50)),
                ('point_type', models.CharField(choices=[('valve', 'Valve'), ('breaker', 'Circuit Breaker'), ('switch', 'Switch')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isolation_points', to='ergon.project')),
            ],
            options={
                'db_table': 'ptw_isolation_point_library',
                'ordering': ['point_code'],
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('permit_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('planned_start_time', models.DateTimeField()),
                ('planned_end_time', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('probability', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('severity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('risk_score', models.PositiveSmallIntegerField(default=1)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('extreme', 'Extreme')], default='low', max_length=10)),
                ('control_measures', models.TextField(blank=True)),
                ('ppe_requirements', models.JSONField(blank=True, default=list)),
                ('safety_checklist', models.JSONField(blank=True, default=dict)),
                ('qr_code', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits_created', to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits_issued', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='ergon.project')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits_received', to=settings.AUTH_USER_MODEL)),
                ('permit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='permit_to_work.permittype')),
            ],
            options={
                'db_table': 'ptw_permit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_type', models.CharField(choices=[('O2', 'Oxygen'), ('CO', 'Carbon Monoxide'), ('H2S', 'Hydrogen Sulfide'), ('CH4', 'Methane')], max_length=10)),
                ('reading', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('unsafe', 'Unsafe')], max_length=10)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('tested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_tests', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_readings', to='permit_to_work.permit')),
            ],
            options={
                'db_table': 'ptw_gas_reading',
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_type', models.CharField(choices=[('issuer', 'Permit Issuer'), ('receiver', 'Permit Receiver'), ('approver', 'Approver'), ('verifier', 'Verifier')], max_length=20)),
                ('signature_payload', models.JSONField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='permit_to_work.permit')),
            ],
            options={
                'db_table': 'ptw_digital_signature',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='permit_to_work.permit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ptw_permit_audit',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PermitCloseout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.JSONField(default=dict)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closeouts_completed', to=settings.AUTH_USER_MODEL)),
                ('permit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closeout', to='permit_to_work.permit')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permit_to_work.closeoutchecklisttemplate')),
            ],
            options={
                'db_table': 'ptw_permit_closeout',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('original_end_time', models.DateTimeField()),
                ('new_end_time', models.DateTimeField()),
                ('extension_hours', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_extensions', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='permit_to_work.permit')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_extensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ptw_permit_extension',
            },
        ),
        migrations.CreateModel(
            name='PermitIsolationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('isolated', 'Isolated'), ('verified', 'Verified'), ('deisolated', 'De-isolated')], default='assigned', max_length=20)),
                ('isolated_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isolated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isolations_performed', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolation_points', to='permit_to_work.permit')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permit_to_work.isolationpointlibrary')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isolations_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ptw_permit_isolation_point',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='closeoutchecklisttemplate',
            name='permit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closeout_templates', to='permit_to_work.permittype'),
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('permit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='permit_to_work.permit')),
            ],
            options={
                'db_table': 'ptw_workflow_instance',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('step_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_assignments', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='permit_to_work.workflowinstance')),
            ],
            options={
                'db_table': 'ptw_workflow_step',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('extreme', 'Extreme')], max_length=10)),
                ('steps', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='permit_to_work.permittype')),
            ],
            options={
                'db_table': 'ptw_workflow_template',
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='permit_to_work.workflowtemplate'),
        ),
        migrations.AddIndex(
            model_name='isolationpointlibrary',
            index=models.Index(fields=['athens_tenant_id', 'point_code'], name='ptw_isolati_athens__16584f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='digitalsignature',
            unique_together={('permit', 'signature_type', 'signatory')},
        ),
        migrations.AddIndex(
            model_name='permitaudit',
            index=models.Index(fields=['permit', '-timestamp'], name='ptw_permit__permit__b87be7_idx'),
        ),
        migrations.AddIndex(
            model_name='permitisolationpoint',
            index=models.Index(fields=['permit', 'status'], name='ptw_permit__permit__061cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='permit',
            index=models.Index(fields=['athens_tenant_id', 'status'], name='ptw_permit_athens__eae31d_idx'),
        ),
        migrations.AddIndex(
            model_name='permit',
            index=models.Index(fields=['permit_number'], name='ptw_permit_permit__359755_idx'),
        ),
        migrations.AddIndex(
            model_name='permit',
            index=models.Index(fields=['created_at'], name='ptw_permit_created_9c10c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'step_id')},
        ),
    ]
