# Generated by Django 5.2.5 on 2025-08-28 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('worker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolboxTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Duration')),
                ('duration_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours')], default='minutes', max_length=10, verbose_name='Duration Unit')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('conducted_by', models.CharField(max_length=255, verbose_name='Conducted By')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20, verbose_name='Status')),
                ('evidence_photo', models.ImageField(blank=True, null=True, upload_to='toolbox_talk_evidence/', verbose_name='Evidence Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_toolbox_talks', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_talks', to='authentication.project')),
            ],
            options={
                'verbose_name': 'Toolbox Talk',
                'verbose_name_plural': 'Toolbox Talks',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ToolboxTalkAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10, verbose_name='Status')),
                ('attendance_photo', models.ImageField(blank=True, null=True, upload_to='toolbox_talk_attendance/', verbose_name='Attendance Photo')),
                ('match_score', models.FloatField(default=0, verbose_name='Match Score')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('toolbox_talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tbt.toolboxtalk', verbose_name='Toolbox Talk')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_talk_attendance', to='worker.worker', verbose_name='Worker')),
            ],
            options={
                'verbose_name': 'Toolbox Talk Attendance',
                'verbose_name_plural': 'Toolbox Talk Attendance Records',
                'unique_together': {('toolbox_talk', 'worker')},
            },
        ),
    ]
