# Generated by Django 5.2.9 on 2026-01-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbt', '0002_add_athens_tenant_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='toolboxtalk',
            name='tbt_toolboxtalk_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='toolboxtalk',
            name='tbt_toolboxtalk_tenant_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='toolboxtalkattendance',
            name='tbt_attendance_tenant_idx',
        ),
        migrations.AlterField(
            model_name='toolboxtalk',
            name='athens_tenant_id',
            field=models.UUIDField(blank=True, help_text='Athens tenant identifier for multi-tenant isolation', null=True),
        ),
        migrations.AlterField(
            model_name='toolboxtalkattendance',
            name='athens_tenant_id',
            field=models.UUIDField(blank=True, help_text='Athens tenant identifier for multi-tenant isolation', null=True),
        ),
    ]
