# Generated by Django 5.1.4 on 2026-01-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbt', '0003_remove_toolboxtalk_tbt_toolboxtalk_tenant_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolboxtalk',
            name='join_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Join Code'),
        ),
        migrations.AddField(
            model_name='toolboxtalk',
            name='qr_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='QR Expires At'),
        ),
        migrations.AddField(
            model_name='toolboxtalk',
            name='qr_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='QR Token'),
        ),
    ]
