# Generated by Django 5.2.14 on 2026-05-08 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbt', '0006_tbt_enhanced_workflow'),
        ('worker', '0003_remove_worker_worker_worker_tenant_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolboxtalk',
            name='discussion_points',
            field=models.JSONField(blank=True, default=list, verbose_name='Discussion Points'),
        ),
        migrations.AlterField(
            model_name='toolboxtalkattendance',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toolbox_talk_attendance', to='worker.worker', verbose_name='Worker'),
        ),
    ]
