# Generated by Django 5.2.14 on 2026-05-12 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('module', models.CharField(default='general', max_length=50)),
                ('project', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation')),
            ],
            options={
                'db_table': 'ai_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('suggestion_type', models.CharField(choices=[('ptw', 'PTW'), ('incident', 'Incident'), ('inspection', 'Inspection'), ('general', 'General')], max_length=20)),
                ('input_text', models.TextField()),
                ('suggestion_data', models.JSONField(default=dict)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('source_language', models.CharField(max_length=10)),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('module', models.CharField(blank=True, max_length=50)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_translations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('input_summary', models.CharField(blank=True, max_length=500)),
                ('success', models.BooleanField(default=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('used_gemini', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', '-created_at'], name='ai_activity_tenant__6c843b_idx'), models.Index(fields=['user', '-created_at'], name='ai_activity_user_id_1e6892_idx')],
            },
        ),
    ]
