# Generated by Django 5.2.11 on 2026-02-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0002_tenant_admin_email_tenant_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteradmin',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masteradmin',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masteradmin',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masteradmin',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='masteradmin',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masteradmin',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteradmin',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='masteradmin',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='masteradmin',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
