# Generated by Django 5.2.11 on 2026-02-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0005_update_masteradmin_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athensauditlog',
            name='action',
            field=models.CharField(choices=[('tenant_created', 'Tenant Created'), ('tenant_updated', 'Tenant Updated'), ('tenant_suspended', 'Tenant Suspended'), ('tenant_reactivated', 'Tenant Reactivated'), ('tenant_synced', 'Tenant Synced'), ('modules_updated', 'Modules Updated'), ('subscription_updated', 'Subscription Updated')], max_length=30),
        ),
        migrations.DeleteModel(
            name='MasterAdmin',
        ),
    ]
