# Generated by Django 5.2.11 on 2026-02-17 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0006_add_tenant_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('hr_workforce', 'HR & Workforce Management'), ('finance', 'Finance & Accounting'), ('crm', 'Customer Relationship Management'), ('inventory', 'Inventory Management'), ('project', 'Project Management'), ('sustainability', 'Sustainability & ESG'), ('other', 'Other')], max_length=50)),
                ('base_url', models.CharField(help_text='Base URL path for the service', max_length=255)),
                ('icon', models.CharField(default='cube', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.JSONField(default=dict, help_text='Service features by tier')),
                ('pricing', models.JSONField(default=dict, help_text='Pricing by tier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('credentials', models.JSONField(default=dict, help_text='Service-specific credentials')),
                ('config', models.JSONField(default=dict, help_text='Service-specific configuration')),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tenants', to='control_plane.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_services', to='control_plane.tenant')),
            ],
            options={
                'db_table': 'tenant_services',
                'ordering': ['-enabled_at'],
                'unique_together': {('tenant', 'service')},
            },
        ),
    ]
