# Generated by Django 5.2.11 on 2026-02-18 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0008_seed_workforce_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True)),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('module_code', models.CharField(choices=[('ergon', 'ERGON'), ('workforce', 'Workforce'), ('ptw', 'Permit to Work'), ('incident', 'Incident Management'), ('safety', 'Safety Observation'), ('training', 'Training')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_modules',
                'indexes': [models.Index(fields=['project_id', 'is_enabled'], name='project_mod_project_93132e_idx'), models.Index(fields=['athens_tenant_id', 'module_code'], name='project_mod_athens__f140ea_idx')],
                'unique_together': {('project_id', 'module_code')},
            },
        ),
    ]
