# Generated by Django 5.2.11 on 2026-02-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0009_projectmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodule',
            name='module_code',
            field=models.CharField(choices=[('ergon_tasks', 'ERGON - Task Management'), ('ergon_planner', 'ERGON - Daily Planner'), ('ergon_followups', 'ERGON - Follow-ups'), ('ergon_advance', 'ERGON - Advance/Expenses'), ('ergon_manpower', 'ERGON - Manpower/Machinery'), ('ergon_ledger', 'ERGON - Financial Ledger'), ('workforce_profile', 'Workforce - Profile Management'), ('workforce_attendance', 'Workforce - Attendance'), ('workforce_leave', 'Workforce - Leave Management'), ('ptw', 'Permit to Work'), ('incident', 'Incident Management'), ('safety', 'Safety Observation'), ('training', 'Training')], max_length=50),
        ),
    ]
