# Generated by Django 5.2.11 on 2026-02-22 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0015_update_tier_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collaboration_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_projects',
            },
        ),
        migrations.CreateModel(
            name='CollaborationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('epc', 'EPC'), ('contractor', 'Contractor'), ('viewer', 'Viewer')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_memberships', to='control_plane.tenant')),
                ('collaboration_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='control_plane.collaborationproject')),
            ],
            options={
                'db_table': 'collaboration_memberships',
                'unique_together': {('collaboration_project', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='CollaborationSharePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('allowed_actions', models.JSONField(default=list)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaboration_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_policies', to='control_plane.collaborationproject')),
            ],
            options={
                'db_table': 'collaboration_share_policies',
                'unique_together': {('collaboration_project', 'domain')},
            },
        ),
    ]
