# Generated by Django 5.2.11 on 2026-02-20 06:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True, unique=True)),
                ('pf_rate', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('esi_rate', models.DecimalField(decimal_places=2, default=Decimal('0.75'), max_digits=5)),
                ('bonus_min_percent', models.DecimalField(decimal_places=2, default=Decimal('8.33'), max_digits=5)),
                ('bonus_max_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('ot_multiplier', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=4)),
                ('min_wage_category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workforce_payroll_settings',
            },
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='check_in',
            new_name='in_time',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='check_out',
            new_name='out_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='remarks',
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave'), ('H', 'Holiday'), ('WO', 'Weekly Off')], default='P', max_length=2),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workforce_department',
                'unique_together': {('athens_tenant_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workforce_designation',
                'unique_together': {('athens_tenant_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('employee_code', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('father_or_husband_name', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('permanent_address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('temporary', 'Temporary')], max_length=20)),
                ('skill_category', models.CharField(blank=True, max_length=100)),
                ('joining_date', models.DateField()),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('uan_number', models.CharField(blank=True, max_length=50)),
                ('esi_number', models.CharField(blank=True, max_length=50)),
                ('pf_applicable', models.BooleanField(default=False)),
                ('esi_applicable', models.BooleanField(default=False)),
                ('lwf_applicable', models.BooleanField(default=False)),
                ('wage_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=20)),
                ('basic_structure', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('da_structure', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hra_structure', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_allowances_structure', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workforce.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workforce.designation')),
            ],
            options={
                'db_table': 'workforce_employee',
            },
        ),
        migrations.CreateModel(
            name='BonusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('accounting_year', models.CharField(max_length=20)),
                ('total_salary_for_year', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.employee')),
            ],
            options={
                'db_table': 'workforce_bonus_record',
            },
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('advance_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('recovered', 'Recovered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.employee')),
            ],
            options={
                'db_table': 'workforce_advance',
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.employee'),
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('fine_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.employee')),
            ],
            options={
                'db_table': 'workforce_fine',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('holiday_date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('national', 'National'), ('festival', 'Festival'), ('restricted', 'Restricted')], max_length=20)),
                ('notification_reference', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workforce_holiday',
                'unique_together': {('athens_tenant_id', 'holiday_date')},
            },
        ),
        migrations.CreateModel(
            name='PayrollCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('cycle_name', models.CharField(max_length=100)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workforce_payroll_cycle',
                'unique_together': {('athens_tenant_id', 'cycle_name')},
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('total_days_worked', models.IntegerField(default=0)),
                ('paid_leave_days', models.IntegerField(default=0)),
                ('unpaid_leave_days', models.IntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('basic_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('da_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hra_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_wages', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esi_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fines', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.employee')),
                ('payroll_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.payrollcycle')),
            ],
            options={
                'db_table': 'workforce_payroll_entry',
            },
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('shift_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('weekly_off_day', models.IntegerField(help_text='0=Monday, 6=Sunday', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_hours_per_day', models.DecimalField(decimal_places=2, default=9, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workforce_shift_schedule',
                'unique_together': {('athens_tenant_id', 'shift_name')},
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.shiftschedule'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['athens_tenant_id', 'status'], name='workforce_e_athens__fe24e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('athens_tenant_id', 'employee_code')},
        ),
        migrations.AlterUniqueTogether(
            name='bonusrecord',
            unique_together={('athens_tenant_id', 'accounting_year', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='payrollentry',
            unique_together={('payroll_cycle', 'employee')},
        ),
    ]
