# Generated by Django 5.2.11 on 2026-02-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0004_migrate_contractor_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contractlabourdeployment',
            new_name='contract_la_athens__7ff256_idx',
            old_name='contract_la_athens__idx',
        ),
        migrations.RenameIndex(
            model_name='contractlabourdeployment',
            new_name='contract_la_project_0ea9eb_idx',
            old_name='contract_la_project_idx',
        ),
        migrations.RenameIndex(
            model_name='contractlabourdeployment',
            new_name='contract_la_contrac_b678b2_idx',
            old_name='contract_la_contrac_idx',
        ),
        migrations.RenameIndex(
            model_name='contractlabourdeployment',
            new_name='contract_la_deploym_49a1f5_idx',
            old_name='contract_la_deploym_idx',
        ),
        migrations.RenameIndex(
            model_name='contractorcompliance',
            new_name='contractor__license_7b0182_idx',
            old_name='contractor_c_license_idx',
        ),
        migrations.RenameIndex(
            model_name='contractorcompliance',
            new_name='contractor__is_comp_59fb1e_idx',
            old_name='contractor_c_complia_idx',
        ),
        migrations.RenameIndex(
            model_name='contractormaster',
            new_name='contractor__athens__1cb5df_idx',
            old_name='contractor_m_athens__idx',
        ),
        migrations.RenameIndex(
            model_name='contractormaster',
            new_name='contractor__company_70c59c_idx',
            old_name='contractor_m_company_idx',
        ),
        migrations.RenameIndex(
            model_name='contractormaster',
            new_name='contractor__email_2c0cb6_idx',
            old_name='contractor_m_email_idx',
        ),
    ]
