# Generated by Django 5.2.13 on 2026-04-17 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_notificationpreference_notification'),
        ('workforce', '0005_rename_contract_la_athens__idx_contract_la_athens__7ff256_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractlabourdeployment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_deployments', to='authentication.project'),
        ),
    ]
