# Generated by Django 5.2.14 on 2026-05-09 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0010_attendance_admin_user_attendance_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by_admin_type',
            field=models.CharField(blank=True, help_text='client/epc/contractor', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization_type',
            field=models.CharField(blank=True, help_text='client/epc/contractor - for filtering', max_length=20),
        ),
    ]
