# Generated by Django 5.2.13 on 2026-05-25 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0012_populate_employee_isolation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Login account provisioned for this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
