# Generated by Django 5.2.11 on 2026-02-24 14:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0021_remove_notificationpreference_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observationID', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reportedBy', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('workLocation', models.CharField(default='', max_length=150)),
                ('activityPerforming', models.CharField(default='', max_length=150)),
                ('contractorName', models.CharField(blank=True, max_length=100, null=True)),
                ('typeOfObservation', models.CharField(choices=[('unsafe_act', 'Unsafe Act'), ('unsafe_condition', 'Unsafe Condition'), ('safe_act', 'Safe Act'), ('near_miss', 'Near Miss'), ('at_risk_behavior', 'At-Risk Behavior'), ('improvement_opportunity', 'Improvement Opportunity'), ('repeat_observation', 'Repeat Observation'), ('ppe_non_compliance', 'PPE Non-Compliance'), ('violation_procedure', 'Violation of Procedure/Permit'), ('training_need', 'Training Need to be Identified'), ('emergency_preparedness', 'Emergency Preparedness')], default='unsafe_act', max_length=50)),
                ('classification', models.JSONField(default=list)),
                ('safetyObservationFound', models.TextField(default='', max_length=1000)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('likelihood', models.IntegerField(choices=[(1, 'Rare'), (2, 'Possible'), (3, 'Likely'), (4, 'Certain')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('riskScore', models.IntegerField(default=1, editable=False)),
                ('correctivePreventiveAction', models.TextField(default='')),
                ('correctiveActionAssignedTo', models.CharField(default='', max_length=100)),
                ('commitmentDate', models.DateField(blank=True, null=True)),
                ('observationStatus', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending_verification', 'Pending Verification'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='open', max_length=50)),
                ('remarks', models.TextField(blank=True, max_length=1000)),
                ('escalation_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_environmental', models.BooleanField(default=False)),
                ('env_incident_type', models.CharField(blank=True, choices=[('spill', 'Spill'), ('emission_exceedance', 'Emission Exceedance'), ('bird_strike', 'Bird Strike'), ('waste_violation', 'Waste Violation'), ('water_contamination', 'Water Contamination'), ('noise_violation', 'Noise Violation')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_safety_observations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_observations', to='authentication.project')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyObservationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='safety_observation_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('before', 'Before Photo'), ('after', 'After Photo'), ('fixed', 'Fixed Photo')], default='before', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('safety_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='safetyobservation.safetyobservation')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
