# Generated by Django 5.2.11 on 2026-02-24 15:18

import django.db.models.deletion
import safetyobservation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safetyobservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyobservation',
            name='athens_tenant_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='safetyobservation',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetyobservation',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_safety_observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safetyobservation',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='safetyobservation',
            name='observationStatus',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('closed', 'Closed')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='safetyobservationfile',
            name='file_type',
            field=models.CharField(default='before', max_length=20),
        ),
        migrations.CreateModel(
            name='SafetyObservationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField()),
                ('file', models.FileField(upload_to=safetyobservation.models.attachment_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('before', 'Before Photo'), ('after', 'After Photo')], default='before', max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='safetyobservation.safetyobservation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
