# Generated by Django 5.2.11 on 2026-02-24 15:18

from django.db import migrations

def backfill_tenant_ids(apps, schema_editor):
    SafetyObservation = apps.get_model('safetyobservation', 'SafetyObservation')
    
    # Backfill from created_by.athens_tenant_id
    for obs in SafetyObservation.objects.filter(athens_tenant_id__isnull=True):
        if obs.created_by and hasattr(obs.created_by, 'athens_tenant_id'):
            obs.athens_tenant_id = obs.created_by.athens_tenant_id
            obs.save(update_fields=['athens_tenant_id'])

def reverse_backfill(apps, schema_editor):
    # No reverse operation needed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('safetyobservation', '0002_safetyobservation_athens_tenant_id_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_tenant_ids, reverse_backfill),
    ]
