# Generated by Django 5.2.11 on 2026-02-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safetyobservation', '0003_backfill_observation_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyobservation',
            name='athens_tenant_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
