# Generated by Django 5.2.11 on 2026-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safetyobservation', '0004_alter_safetyobservation_athens_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyobservation',
            name='target_close_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
